default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: admin
  password: n1502803a

development:
  <<: *default
  database: aiis_development

test:
  <<: *default
  database: aiis_test

production:
  <<: *default
  database: aiis_production